package GUI;

import BE.BEFireman;
import BLL.BLLFireman;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Team Kawabunga
 */
public class CheckUdView extends javax.swing.JFrame {

    BLLFireman bllFireman;
    ArrayList<BEFireman> allFiremen = new ArrayList<>();
    private JPanel main;
    private int width;
    private int height;

    /**
     * Creates new form CheckUD
     */
    public CheckUdView() {
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        bllFireman = BLLFireman.getInstance();
        this.setUndecorated(true);
        this.setResizable(false);
        setResizable(false);
        this.setTitle("CHECK UD SCREEN");
        getContentPane().setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        pack();
        width = (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        height = (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        main = getBorderLayout();
        this.add(main);
    }

    private JPanel getBorderLayout() {
        JPanel p = new JPanel();
        BorderLayout blayout = new BorderLayout();
        p.setLayout(blayout);
        p.add(getPanelLayout(), BorderLayout.CENTER);
        return p;
    }

    private JPanel getPanelLayout() {
        int amount = 1;
        allFiremen = bllFireman.getAllfiremen();
        FlowLayout flayout = new FlowLayout();
        flayout.setHgap(30); // definer afstanden imellem grupperne
        JPanel p = new JPanel(flayout);
        p.setBorder(BorderFactory.createLineBorder(Color.red));
        for (int i = 0; i < 4; i++) {
            JPanel panel = new JPanel();
            GridLayout glayout = new GridLayout(8, 1);
            glayout.setVgap(10);
            panel.setPreferredSize(new Dimension(width / 5, height));
            panel.setLayout(glayout);
            for (BEFireman fm : allFiremen) {
                panel.setBackground(getColorTeam(i));
                JButton b = new firemanButton(fm);
                if (fm.getTeam() == amount) {
                    panel.add(b);
                }
            }
            panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            p.add(panel);
            amount++;
        }
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private Color getColorTeam(int i) {
        Color myColor = Color.red;
        switch (i) {
            case 1:
                myColor = Color.white;
                break;
            case 2:
                myColor = Color.blue;
                break;
            case 3:
                myColor = Color.yellow;
                break;
        }
        return myColor;
    }

    private class firemanButton extends JButton {

        String name;
        BEFireman localFireman;

        public firemanButton(BEFireman fm) {
            localFireman = fm;
            this.name = fm.getMedarbjeder().getFornavn();
            this.setBackground(getColor());
            this.setText(name);
        }

        private Color getColor() {
            Color myColor = new Color(255, 215, 0);
            switch (localFireman.getTeam()) {
                case 1:
                    myColor = new Color(255, 99, 71);
                    break;
                case 2:
                    myColor = new Color(245, 245, 220);
                    break;
                case 3:
                    myColor = new Color(173, 216, 230);
                    break;
            }
            return myColor;
        }

        private void setColor() {
            this.setBackground(getColor());
            repaint();
        }

//        public void changebit() {
//            localFireman.setIsCheckedin(!localFireman.isCheckedin());
//            bllFireman.changeBit(localFireman);
////            setColor();
//        }
        public void updateLocalFireman(BEFireman lfm) {
            localFireman = lfm;
            this.setBackground(getColor());
        }
    }
}
