package GUI;

import BE.BEAppearance;
import BE.BEError;
import BE.BEVehicle;
import BLL.BLLVehicle;
import BLL.BLLReport;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Team Kawabunga
 */
public class HLErrorReport extends javax.swing.JFrame {
BLLVehicle bllVehicle;
    BLLReport bllreport;
    /**
     * Creates new form HLErrorReport
     */
    public HLErrorReport() {
        bllVehicle = BLLVehicle.getInstance();
        bllreport = BLLReport.getInstance();
        initComponents();
        initOtherComponents();
        fillCboxKøretøj();
        this.setTitle("Reparation/Køretøjsmangler");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        lblKøtj = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCourse = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtOutofOrder = new javax.swing.JTextField();
        txtUrgent = new javax.swing.JTextField();
        txtInDueTime = new javax.swing.JTextField();
        txtWash = new javax.swing.JTextField();
        btnAcknowledge = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();
        cboxKøretøj = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtError.setColumns(20);
        txtError.setRows(5);
        jScrollPane1.setViewportView(txtError);

        jLabel2.setText("FEJL:");

        lblKøtj.setText("Køretøj:");

        txtCourse.setColumns(20);
        txtCourse.setRows(5);
        jScrollPane2.setViewportView(txtCourse);

        jLabel5.setText("Evt. årsag:");

        jLabel6.setText("Ud af drift:");

        jLabel7.setText("Haster:");

        jLabel8.setText("Ved lejlighed:");

        jLabel9.setText("Branddragter til vask:");

        btnAcknowledge.setText("Bekræft");

        btnDone.setText("Færdig / Ingen fejl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtOutofOrder)
                                .addComponent(txtUrgent)
                                .addComponent(txtInDueTime)
                                .addComponent(txtWash, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnAcknowledge)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDone)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKøtj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxKøretøj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKøtj)
                    .addComponent(cboxKøretøj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtOutofOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtUrgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtInDueTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtWash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcknowledge)
                    .addComponent(btnDone))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcknowledge;
    private javax.swing.JButton btnDone;
    private javax.swing.JComboBox cboxKøretøj;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblKøtj;
    private javax.swing.JTextArea txtCourse;
    private javax.swing.JTextArea txtError;
    private javax.swing.JTextField txtInDueTime;
    private javax.swing.JTextField txtOutofOrder;
    private javax.swing.JTextField txtUrgent;
    private javax.swing.JTextField txtWash;
    // End of variables declaration//GEN-END:variables

    private void fillCboxKøretøj(){
     for (BEVehicle veh : bllVehicle.GetVehicles()){
         cboxKøretøj.addItem(veh);
     }
     cboxKøretøj.setSelectedIndex(-1);
 }
    
    private void initOtherComponents() {
        lblHeader.setText("Reparation/Køretøjsmangler");
        btnAcknowledge.setText("Bekræft");
        btnAcknowledge.setEnabled(true);
        btnAcknowledge.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                if (!txtError.getText().isEmpty() && cboxKøretøj.getSelectedIndex() != -1){
                bllreport.createErrorReport(errorAsBE(), (BEVehicle)cboxKøretøj.getSelectedItem());
                JOptionPane.showMessageDialog(null, "Fejl rapport sendt");
                cboxKøretøj.setSelectedIndex(-1);
                txtError.setText("");
                txtCourse.setText("");
                txtInDueTime.setText("");
                txtOutofOrder.setText("");
                txtUrgent.setText("");
                txtWash.setText("");
                }
                else
                {
                    msgbox("Indtast venligst en fejl");
                }
            }
        });
        btnDone.setText("Færdig / Ingen fejl");
        btnDone.setEnabled(true);
        btnDone.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LoginView frame = new LoginView();
                frame.setVisible(true);
                JOptionPane.showMessageDialog(null,"Tak for bekræftigelse");
                dispose();
            }
        });
    }
    
    private void msgbox(String message){
        JOptionPane.showMessageDialog(this, message);
    }

    private BEError errorAsBE() {
        String error = txtError.getText();
        String course = txtCourse.getText();
        String ooo = txtOutofOrder.getText();
        String urgent = txtUrgent.getText();
        String idt = txtInDueTime.getText();
        String wash = txtWash.getText();

        BEError be = new BEError(error, course, ooo, urgent, idt, wash);
        return be;
    }
}
