package GUI;

import BE.BEMateriel;
import BLL.BLLUsage;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Shadowleet
 */
public class HLForbrugRapport extends javax.swing.JFrame {

    BLLUsage bllusage;
    BEMateriel m;
    ArrayList<BEMateriel> allMats = new ArrayList<>();
    private JPanel main;
    private int width = 2;
    private int height = allMats.size() / width;

    /**
     * Creates new form HLErrorRapport
     */
    public HLForbrugRapport() {
        initComponents();
        bllusage = BLLUsage.getInstance();

        this.setTitle("Holdleder Forbrugs Rapport");
        this.setLocationRelativeTo(null);
        main = getBorderLayout();
        this.add(main);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    private JPanel getBorderLayout() {
        JPanel p = new JPanel();
        p.setLayout(new BorderLayout());
        p.add(getGridLayout(), BorderLayout.CENTER);
        return p;
    }

    private JPanel getGridLayout() {
        JPanel p = new JPanel();
        GridLayout gl = new GridLayout(width, height - 1);
        p.setLayout(gl);
        p.add(getGroupLayout());
        return p;
    }

    private JPanel getGroupLayout() {
        allMats = bllusage.getAllMats();
        JPanel p = new JPanel();
        System.out.println(allMats.get(0).getName());
        for (BEMateriel mat : allMats) {
            JLabel label = new JLabel();
            JTextField tf = new JTextField();
            JPanel panel = new ForbrugPanel(mat);
            GroupLayout layout = new GroupLayout(panel);
            layout.setAutoCreateGaps(true);
            layout.setAutoCreateContainerGaps(true);
            /**
             * MANGLER DET RIGTIGE COMPONENT! FRA FORBRUG? at "her"
             */
//            layout.setHorizontalGroup(layout.createSequentialGroup().addComponent("her"));
//            layout.setVerticalGroup(layout.createSequentialGroup().addComponent("her"));
            p.add(panel);
        }
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
    // Variables declaration - do not modify                     
    // End of variables declaration                   
private class ForbrugPanel extends javax.swing.JPanel {

        private String name;
//        private int amount;
//        private BEMateriel mats;
        private JLabel label = new JLabel();
        private JTextField tf = new JTextField();

        /**
         * Creates new form ForbrugPanel
         */
        public ForbrugPanel(BEMateriel m) {
            this.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            this.name = m.getName();
            this.add(label);
            label.setText(name);
            this.add(tf);
            tf.setText("");
        }
//
//        public JLabel getLabel() {
//            return label;
//        }
//
//        public JTextField getText() {
//            return tf;
//        }
    }
}