package GUI;

import BE.BEAppearance;
import BE.BEMateriel;
import BE.BEUsage;
import BLL.BLLUsage;
import com.sun.org.apache.xalan.internal.xsltc.compiler.sym;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.regex.Pattern;

/**
 *
 * @author Team Kawabunga
 */
public class HLUsageRapport extends javax.swing.JFrame {

    BEUsage beusage;
    BEAppearance appear;
    BLLUsage bllUsage;

    /**
     * Creates new form HLOdinRapport
     *
     * @param a
     */
    public HLUsageRapport(BEAppearance a) {
        bllUsage = BLLUsage.getInstance();
        appear = a;
        initComponents();
        initOtherComponents();
        this.setTitle("FORBRUG TIL ODIN RAPPORT");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHTrør = new javax.swing.JTextField();
        txtStråleslanger = new javax.swing.JTextField();
        txtBSlanger = new javax.swing.JTextField();
        txtCSlanger = new javax.swing.JTextField();
        txtRøgdykker = new javax.swing.JTextField();
        txtFlasker = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFrigørelse = new javax.swing.JTextField();
        txtOvertryk = new javax.swing.JTextField();
        txtVand = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSkum = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtLys = new javax.swing.JTextField();
        txtPulverslukker = new javax.swing.JTextField();
        txtKulsyreslukker = new javax.swing.JTextField();
        txtFlyde = new javax.swing.JTextField();
        txtKattegrus = new javax.swing.JTextField();
        txtAbsorbW = new javax.swing.JTextField();
        txtPresseninger = new javax.swing.JTextField();
        txtCobraslukker = new javax.swing.JTextField();
        txtMængde = new javax.swing.JTextField();
        txtSpænde = new javax.swing.JTextField();
        btnAcknowledge = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setText("FORBRUG ");

        jLabel2.setText("HT rør");

        jLabel3.setText("Stråleslanger");

        jLabel4.setText("B-Slanger");

        jLabel5.setText("c-Slanger");

        jLabel6.setText("Røgdykkerapp.");

        jLabel7.setText("Flasker (300 bar)");

        jLabel8.setText("Frigørelsesmateriel");

        jLabel9.setText("Overtryksventiler");

        jLabel10.setText("Vandforbrug");

        jLabel11.setText("Skumvæske");

        jLabel12.setText("Lysmateriel");

        jLabel13.setText("Pulverslukker");

        jLabel14.setText("Kulsyreslukker");

        jLabel15.setText("Flydespærringer");

        jLabel16.setText("Absordan \"kattegrus\"");

        jLabel17.setText("Absorbent W");

        jLabel18.setText("Engangspresseninger");

        jLabel19.setText("Cobra slukker");

        jLabel20.setText("Mængde opsamlet");

        jLabel21.setText("Spændelågsflade");

        btnAcknowledge.setText("Bekræft forbrug");

        jLabel22.setText("Liter");

        jLabel23.setText("Liter");

        jLabel24.setText("Kg.");

        jLabel25.setText("Stk.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAcknowledge)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFrigørelse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFlasker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtStråleslanger, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHTrør, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(txtBSlanger)
                                    .addComponent(txtCSlanger)
                                    .addComponent(txtOvertryk)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRøgdykker, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtVand, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addGap(0, 125, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSkum, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFlyde, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKulsyreslukker, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPulverslukker, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLys, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSpænde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMængde, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAbsorbW, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKattegrus, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCobraslukker, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPresseninger, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(lblHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblHeader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHTrør, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtLys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStråleslanger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtPulverslukker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBSlanger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtKulsyreslukker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCSlanger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtFlyde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtRøgdykker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtKattegrus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFlasker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtAbsorbW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFrigørelse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtPresseninger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtOvertryk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtCobraslukker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtVand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtMængde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSkum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtSpænde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25))
                .addGap(26, 26, 26)
                .addComponent(btnAcknowledge)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcknowledge;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTextField txtAbsorbW;
    private javax.swing.JTextField txtBSlanger;
    private javax.swing.JTextField txtCSlanger;
    private javax.swing.JTextField txtCobraslukker;
    private javax.swing.JTextField txtFlasker;
    private javax.swing.JTextField txtFlyde;
    private javax.swing.JTextField txtFrigørelse;
    private javax.swing.JTextField txtHTrør;
    private javax.swing.JTextField txtKattegrus;
    private javax.swing.JTextField txtKulsyreslukker;
    private javax.swing.JTextField txtLys;
    private javax.swing.JTextField txtMængde;
    private javax.swing.JTextField txtOvertryk;
    private javax.swing.JTextField txtPresseninger;
    private javax.swing.JTextField txtPulverslukker;
    private javax.swing.JTextField txtRøgdykker;
    private javax.swing.JTextField txtSkum;
    private javax.swing.JTextField txtSpænde;
    private javax.swing.JTextField txtStråleslanger;
    private javax.swing.JTextField txtVand;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    private void initOtherComponents() {
        lblHeader.setText("Indtast det brugte materiel");
        btnAcknowledge.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                usage();
                dispose();
                openErrorReport(appear);
            }
        });
    }

    private boolean test(String s) {
        return !s.isEmpty() && !Pattern.matches("[a-zA-Z]+", s);
    }

    /**
     *
     * @return BEUsage with the added usage.
     */
    private void usage() {

        int htrør = test(txtHTrør.getText()) ? Integer.parseInt(txtHTrør.getText()) : 0;
        int stråle = test(txtStråleslanger.getText()) ? Integer.parseInt(txtStråleslanger.getText()) : 0;
        int bslanger = test(txtBSlanger.getText()) ? Integer.parseInt(txtBSlanger.getText()) : 0;
        int cslanger = test(txtCSlanger.getText()) ? Integer.parseInt(txtCSlanger.getText()) : 0;
        int røgdykker = test(txtRøgdykker.getText()) ? Integer.parseInt(txtRøgdykker.getText()) : 0;
        int flasker = test(txtFlasker.getText()) ? Integer.parseInt(txtFlasker.getText()) : 0;
        int frigør = test(txtFrigørelse.getText()) ? Integer.parseInt(txtFrigørelse.getText()) : 0;
        int overtryk = test(txtOvertryk.getText()) ? Integer.parseInt(txtOvertryk.getText()) : 0;
        int lys = test(txtLys.getText()) ? Integer.parseInt(txtLys.getText()) : 0;
        int pulver = test(txtPulverslukker.getText()) ? Integer.parseInt(txtPulverslukker.getText()) : 0;
        int kulsyre = test(txtKulsyreslukker.getText()) ? Integer.parseInt(txtKulsyreslukker.getText()) : 0;
        int flyde = test(txtFlyde.getText()) ? Integer.parseInt(txtFlyde.getText()) : 0;
        int kattegrus = test(txtKattegrus.getText()) ? Integer.parseInt(txtKattegrus.getText()) : 0;
        int absorb = test(txtAbsorbW.getText()) ? Integer.parseInt(txtAbsorbW.getText()) : 0;
        int press = test(txtPresseninger.getText()) ? Integer.parseInt(txtPresseninger.getText()) : 0;
        int cobra = test(txtCobraslukker.getText()) ? Integer.parseInt(txtCobraslukker.getText()) : 0;
        int vand = test(txtVand.getText()) ? Integer.parseInt(txtVand.getText()) : 0;
        int skum = test(txtSkum.getText()) ? Integer.parseInt(txtSkum.getText()) : 0;
        int mængde = test(txtMængde.getText()) ? Integer.parseInt(txtMængde.getText()) : 0;
        int spænde = test(txtSpænde.getText()) ? Integer.parseInt(txtSpænde.getText()) : 0;

        for (BEMateriel m : bllUsage.getAllMats()) {
            if (m.getName().equals("HT rør")) {
                if (htrør > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, htrør);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Strålerør")) {
                if (stråle > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, stråle);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("B-Slanger")) {
                if (bslanger > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, bslanger);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("C-Slanger")) {
                if (cslanger > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, cslanger);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Røgdykkerapp.")) {
                if (røgdykker > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, røgdykker);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Flasker(300 bar)")) {
                if (flasker > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, flasker);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Frigørelsemateriel")) {
                if (frigør > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, frigør);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Overtryksventiler")) {
                if (overtryk > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, overtryk);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Lysmateriel")) {
                if (lys > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, lys);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Pulverslukker")) {
                if (pulver > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, pulver);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Kulsyreslukker")) {
                if (kulsyre > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, kulsyre);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Flydespærringer")) {
                if (flyde > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, flyde);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Absordan 'kattegrus'")) {
                if (kattegrus > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, kattegrus);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Absobent W")) {
                if (absorb > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, absorb);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Engangspressening")) {
                if (press > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, press);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Cobraslukker")) {
                if (cobra > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, cobra);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Vand")) {
                if (vand > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, vand);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Skum")) {
                if (skum > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, skum);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Opsamletmængde")) {
                if (mængde > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, mængde);
                    createUsageReport(bu);
                }
            }
            if (m.getName().equals("Spændelågsflade")) {
                if (spænde > 0) {
                    BEUsage bu = new BEUsage(appear.getEvaNo(), m, spænde);
                    createUsageReport(bu);
                }
            }
        }
    }

    /**
     * sends the information to the BLL with the BEUsage
     *
     * @param u
     */
    private void createUsageReport(BEUsage u) {
        bllUsage.createReport(u);
    }

    /**
     * Opens a new frame
     */
    private void openErrorReport(BEAppearance a) {
        HLErrorReport frame = new HLErrorReport(a);
        frame.setVisible(true);
    }
}
